# ===============================
# IDENTIFICACIÓN DEL MICROSERVICIO
# ===============================
spring:
  application:
    name: proyectos-servicio

  # ===============================
  # CONFIGURACIÓN DE LA BASE DE DATOS
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_academico
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  # ===============================
  # CONFIGURACIÓN JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update   # update, create, create-drop, validate
    show-sql: true        # Mostrar SQL en consola
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ===============================
  # SEGURIDAD (Spring Security por defecto)
  # ===============================
  security:
    user:
      name: admin
      password: admin123

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server:
  port: 8081