### Registro de usuario
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "correo": "juan@example.com",
  "contrasena": "123456",
  "carrera": "Ing. Sistemas",
  "intereses": "Python, IA",
  "estado": "activo"
}