# ===============================
# IDENTIFICACIÓN DEL MICROSERVICIO
# ===============================
spring:
  application:
    name: usuario-servicio

  # ===============================
  # CONFIGURACIÓN DE LA BASE DE DATOS
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/hackthon_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  # ===============================
  # CONFIGURACIÓN JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update   # update, create, create-drop, validate
    show-sql: true        # Mostrar SQL en consola
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ===============================
  # SEGURIDAD (Spring Security por defecto)
  # ===============================
  security:
    user:
      name: admin
      password: admin123

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server:
  port: 8080

# ===============================
# CONFIGURACIÓN JWT
# ===============================
jwt:
  secret: "ilWA8gIe58CndFA0hTIHwAUyVos9FmlgDZZuNvjmC2o="
  expiration: 36000000  # 10 horas en milisegundos